site_name: Gateway Adventure APP
site_url: https://gatewayadventure.app

theme:
  favicon: images/favicon.png
  name: material
  logo: images/logo.png
  palette:
    scheme: default
    primary: custom
    accent: custom
  font:
    text: Lora
    code: Roboto Mono

extra_css:
  - styles/extra.css
  - styles/toc-only.css
  - styles/custom.css
  - styles/flickity.min.css



extra_javascript:
  - javascripts/replace-terms.js
  - javascripts/flickity.pkgd.min.js

  


markdown_extensions:
  - pymdownx.extra

use_directory_urls: false

nav:
  - Home: index.md
  - About: about.md
  - Contact & Links: contact.md
  - Privacy Policy: privacy-policy.md
  - Download: download.md
  