site_name: Gateway Adventure APP
site_url: https://gatewayadventureapp.github.io

theme:
  favicon: images/favicon.png
  name: material
  logo: images/logo.png
  palette:
    scheme: default
    primary: custom
    accent: custom
  font:
    text: Lora
    code: Roboto Mono

extra_css:
  - styles/extra.css
  - styles/toc-only.css
  - styles/custom.css

extra_javascript:
  - javascripts/replace-terms.js



markdown_extensions:
  - pymdownx.extra

use_directory_urls: false

nav:
  - Home: index.md
  - Contact: contact.md
  - Privacy Policy: privacy-policy.md
  - Download: download.md